//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHR.PMS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eHR.PMS.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600000.
        /// </summary>
        public static string AUTO_SAVE_INTERVAL {
            get {
                return ResourceManager.GetString("AUTO_SAVE_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300000.
        /// </summary>
        public static string MAIN_MENU_REFRESH_INTERVAL {
            get {
                return ResourceManager.GetString("MAIN_MENU_REFRESH_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appraisal is approved..
        /// </summary>
        public static string MSG_APPRAISAL_APPROVED {
            get {
                return ResourceManager.GetString("MSG_APPRAISAL_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the rights to view the appraisal..
        /// </summary>
        public static string MSG_APPRAISAL_NO_ACCESS {
            get {
                return ResourceManager.GetString("MSG_APPRAISAL_NO_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The appraisal is rejected. It will be routed to the employee for re-submission..
        /// </summary>
        public static string MSG_APPRAISAL_REJECTED {
            get {
                return ResourceManager.GetString("MSG_APPRAISAL_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your goals will be submitted to your Manager for approval. You will not be able to edit your goals from this point. Do you want to proceed?.
        /// </summary>
        public static string MSG_APPRAISAL_SUBMISSION {
            get {
                return ResourceManager.GetString("MSG_APPRAISAL_SUBMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your appraisal is submitted..
        /// </summary>
        public static string MSG_APPRAISAL_SUBMITTED {
            get {
                return ResourceManager.GetString("MSG_APPRAISAL_SUBMITTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process approval for appraisal. Please try again or contact IT Department..
        /// </summary>
        public static string MSG_APPROVAL_FAIL {
            get {
                return ResourceManager.GetString("MSG_APPROVAL_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have clicked “Approve” and the goals of [%EMPLOYEE_NAME%] will be sent to the Level 2 Manager for approval. You will not be able to edit this document from this point. Do you want to proceed?.
        /// </summary>
        public static string MSG_APPROVE_LEVEL1 {
            get {
                return ResourceManager.GetString("MSG_APPROVE_LEVEL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have clicked “Approve” and the [%APPRAISAL_STAGE_NAME%] phase of [%EMPLOYEE_NAME%] will be completed. You will not be able to edit this document from this point. Do you want to proceed?.
        /// </summary>
        public static string MSG_APPROVE_LEVEL2 {
            get {
                return ResourceManager.GetString("MSG_APPROVE_LEVEL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to approve?.
        /// </summary>
        public static string MSG_APPROVE_SUBMISSION {
            get {
                return ResourceManager.GetString("MSG_APPROVE_SUBMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All information that are not saved will be discarded. Are you sure you want to return to the main menu?.
        /// </summary>
        public static string MSG_CANCEL {
            get {
                return ResourceManager.GetString("MSG_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the neccessary rights to access the function. Please contact HR Department..
        /// </summary>
        public static string MSG_FUNCTIONS_NO_ACCESS {
            get {
                return ResourceManager.GetString("MSG_FUNCTIONS_NO_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save appraisal information. Please try again or contact IT Department..
        /// </summary>
        public static string MSG_NEXT_FAIL {
            get {
                return ResourceManager.GetString("MSG_NEXT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal information is saved successfully..
        /// </summary>
        public static string MSG_NEXT_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_NEXT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appraisal record found. Please try again or contact IT Department..
        /// </summary>
        public static string MSG_NO_APPRAISAL_FOUND {
            get {
                return ResourceManager.GetString("MSG_NO_APPRAISAL_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to reject?.
        /// </summary>
        public static string MSG_REJECT_SUBMISSION {
            get {
                return ResourceManager.GetString("MSG_REJECT_SUBMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save appraisal information. Please try again or contact IT Department..
        /// </summary>
        public static string MSG_SAVE_FAIL {
            get {
                return ResourceManager.GetString("MSG_SAVE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal information is saved successfully..
        /// </summary>
        public static string MSG_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully saved your draft. Please be reminded to submit your goal document for your Manager&apos;s review by [%DEADLINE%]..
        /// </summary>
        public static string MSG_SAVE_SUCCESS_CAREER_DEVELOPMENT {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESS_CAREER_DEVELOPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully saved your draft. Please be reminded to submit your goal document for your Manager&apos;s review by [%DEADLINE%]..
        /// </summary>
        public static string MSG_SAVE_SUCCESS_CORE_VALUE {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESS_CORE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully saved your draft. Please be reminded to submit your goal document for your Manager&apos;s review by [%DEADLINE%]..
        /// </summary>
        public static string MSG_SAVE_SUCCESS_KPI {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESS_KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully saved your draft. Please be reminded to submit your goal document for your Manager&apos;s review by [%DEADLINE%]..
        /// </summary>
        public static string MSG_SAVE_SUCCESS_PERFORMANCE_COACHING {
            get {
                return ResourceManager.GetString("MSG_SAVE_SUCCESS_PERFORMANCE_COACHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update cycle information now?.
        /// </summary>
        public static string MSG_UPDATE_CYCLE {
            get {
                return ResourceManager.GetString("MSG_UPDATE_CYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal is not in pending appoval status..
        /// </summary>
        public static string MSG_WRONG_STATUS_APPROVAL {
            get {
                return ResourceManager.GetString("MSG_WRONG_STATUS_APPROVAL", resourceCulture);
            }
        }
    }
}
